### ISSUE TITLE
英德反了

### ISSUE THREAD

**Issue by JoySR** [Kirkkt/german-flashcard#4]
https://github.com/Kirkkt/german-flashcard/blob/ea1b4b58a2dff9737cf5d73f6c223af00c29a36e/all-words.txt#L160

https://github.com/Kirkkt/german-flashcard/blob/ea1b4b58a2dff9737cf5d73f6c223af00c29a36e/all-words.txt#L161

**Comment by Kirkkt** [comment]
fixed
